### ISSUE TITLE
[Plan] add support OpenVoice

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#100]
## TODOs
- [x] add openvoice model/dcls/downloader
- [x] add openvoice handler
- [x] add openvoice postprocess
- [x] add openvoice api
- [x] support `vc_config` for all tts apis

**Comment by wenyangchou** [comment]
这个有方案 或者 思路吗

**Comment by zhzLuke96** [comment]
> 这个有方案 或者 思路吗

现在pipeline重构完了，实现这个应该挺简单的

大概就是把 openvoice 库引进来，然后在 生成pipeline 上加一个调用模型 [ToneColorConverter](https://github.com/myshell-ai/OpenVoice/blob/2739f7dfc06f8131ca1e53c73d56985014599e76/openvoice/api.py#L101C1-L101C46) 的 AudioProcessor ，应该就行了

其他可能还得加下模型下载脚本啥的

**Comment by zhzLuke96** [comment]
done
