### ISSUE TITLE
[Feature] Improve streaming results

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#70]
### 功能描述

相关 #5

# 问题
stream api 已实现，但是有未知原因导致生成结果不理想有杂音

tts 生成:
https://github.com/lenML/ChatTTS-Forge/assets/37396659/ac961b7b-dbd9-4f81-a106-a486051e45a5

流式生成:
https://github.com/lenML/ChatTTS-Forge/assets/37396659/a602e813-7059-474a-a603-86fd9ab6af05

# todo list
- [x] fix stream generate bug
- [x] add stream unit tests
- [x] All APIs try to support stream mode

### 可能的解决方案

可能需要依赖上游代码库修复
