### ISSUE TITLE
[Plan] support more tts models

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#90]
# PLAN desc
支持更多 tts models

由于目前主要基于 chattts 开发，部分模块对其有依赖，需要逐个解离
- 需要区分不同模型的能力问题，涉及 Special tokens and refiners
- 加载多模型可能需要引入自动unload检测
- tn管道需要支持函数可拔插

##  TODOs
- [x] refactor Speaker 模块: 支持多种模型，并支持内嵌 audio
    - [x] 实现 speaker 序列化反序列化，消除 .pt 模块依赖
    - [ ] #104
- [x] refactor generate 模块 #91
- [x] refactor model 模块 #91
- [x] refactor TN 模块 #91
- [x] add support: fish speech 
    - ref: https://github.com/fishaudio/fish-speech
- [x] add support: CosyVoice
    - ref: https://github.com/FunAudioLLM/CosyVoice

**Comment by zhzLuke96** [comment]
refs #89

**Comment by zhzLuke96** [comment]
added 1835565997e2b8ed7f23c7e96bb3cda9ea41d59e af9efdfd2ca00216afc0db9ef9d378a41a8d44ee c8905df4fc7dc780104144728773b1c4ce655f95

fish speech 推理部分已接入，但是效果有点感人...😓 暂时不推进了，有兴趣调试的可以在 modules.core.models.tts.FishSpeechModel 模块测试
