### ISSUE TITLE
[Plan] Enhanced post-processing pipeline

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#91]
# PLAN desc
增强后处理流水线，方便增加更多后处理模块
比如 open voice 或者 rvc

## TODOs
- [x] Implementing synthesis pipeline
- [x] support batch generate in stream mode
- [x] refactor Adjuster / Enhancer / AudioHandler
- [x] refactor api => pipeline
- [x] refactor webui => pipeline
- [x] 引入了 wetext 用于TN阶段处理英语文本 

## refs TODOs
- [ ] #100
- [ ] #101
- [x] #90

**Comment by zhzLuke96** [comment]
refs #72

**Comment by zhzLuke96** [comment]
done
