### ISSUE TITLE
[Plan] support ASR 

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#92]
# PLAN desc
增加 ASR 支持

# TODOs
- [x] add ASR handler
- [x] add support Whisper
- [x] add ASR api `v1/audio/transcriptions`
- [ ] #122
- [ ] #123

**Comment by zhzLuke96** [comment]
refs #36
